# Generated by Django 5.2.3 on 2025-07-03 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financiadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('is_radiofarmaco', models.BooleanField(default=False)),
                ('is_insumo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Prestación',
                'verbose_name_plural': 'Prestaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('financiadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.financiadora')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('financiadora', models.CharField(blank=True, max_length=100, null=True, verbose_name='Financiadora')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prestacion', models.CharField(max_length=100)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje_convenio', models.IntegerField(verbose_name='Porcentaje de cobertura')),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prestacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.prestacion')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app.presupuesto')),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('prestaciones', models.ManyToManyField(blank=True, to='app.prestacion')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.servicio')),
            ],
            options={
                'verbose_name': 'Estudio',
                'verbose_name_plural': 'Estudios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConvenioPrestaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.IntegerField(verbose_name='Porcentaje de Cobertura')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('financiadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.financiadora')),
                ('prestacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.prestacion')),
            ],
            options={
                'verbose_name': 'Cobertura de Financiadora con Prestación',
                'verbose_name_plural': 'Coberturas de Financiadora con Prestaciones',
                'indexes': [models.Index(fields=['financiadora', 'prestacion', 'fecha_inicio'], name='app_conveni_financi_dd5bff_idx'), models.Index(fields=['financiadora', 'prestacion', 'fecha_fin'], name='app_conveni_financi_a751fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='PrestacionPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('prestacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='app.prestacion')),
            ],
            options={
                'verbose_name': 'Precio de Prestación',
                'verbose_name_plural': 'Precios de Prestaciones',
                'indexes': [models.Index(fields=['prestacion', 'fecha_inicio'], name='app_prestac_prestac_f755db_idx'), models.Index(fields=['prestacion', 'fecha_fin'], name='app_prestac_prestac_18591b_idx')],
            },
        ),
    ]
